name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: rust:latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894
      with:
        key: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose